server:
  port: 8801
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 192.168.137.128
    port: 5672
    username: admin
    password: 123
  cloud:
    nacos: #设置注册中心
      discovery:
        server-addr: localhost:8848 #配置nacos地址
        username: yangz
        password: 123
    stream:
      bindings: # 服务的整合处理
        myChannel-out-0: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”

